### ISSUE TITLE
Lumma

### ISSUE THREAD

**Issue by weegee12** [YaLTeR/BunnymodXT#478]
![image](https://github.com/YaLTeR/BunnymodXT/assets/108377469/8542a9ac-7273-450c-bc6c-45a26c0564d0)
self explanatory, the dll is actually a lumma file that upon double clicking steals every single one of your passwords

**Comment by khanghugo** [comment]
This is extremely serious. I will tag @YaLTeR here and wait for him to resolve it.

**Comment by YaLTeR** [comment]
If you get the DLLs from an official source (this GitHub's releases page for example) then it should be clean because it's literally built by GitHub from the source code in this repository with nothing extra. So it's either a false flag (very likely), or you got it infected elsewhere.

**Comment by SmileyAG** [comment]
@weegee12 Let's be honest, modern AVs are also a malware itself, there are plenty of examples when some tools / games were falsely branded due to some stupid antiviruses
I don’t even have to look far for an example: https://github.com/FWGS/xash3d-fwgs/issues/1385

If you have doubts, you can always compile source code from GitHub Actions or manually and compare with release build by using https://github.com/google/bindiff and reverse-engineering tools like https://github.com/NationalSecurityAgency/ghidra or [IDA Pro](https://hex-rays.com/ida-pro/) to see for the presence of extra code in the release version, and you will at understand that what you claimed is nonsense

**Comment by a1batross** [comment]
@SmileyAG the solution to this is basically kept behind the paywall.

To make most AVs not give false-positives on your binaries, you have to get a certificate. There is unfortunately no certificate authority that gives free or cheap keys for FOSS projects

That's too much of a hassle for FOSS developers who are usually enthusiasts, when the user can compile software themselves using the same tools and compare the binaries or just migrate away from Windows. ;)
