### ISSUE TITLE
Give an error and close the game if metamod is enabled

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/BunnymodXT#501]
I think there are lots of potentials for BXT to be casually used by mappers because of very helpful HUD info.

The problem now is that most people are relying on AmdModX for basic features like checkpoint or hook or fast noclip to move around.

AmdModX uses MetaMod in between the game and server DLL. So, BXT injection right now would crash the game.

If BunnymodXT is injected, maybe there is a way to force the game to load the normal DLLs. It will be very convenient for most people.

**Comment by khanghugo** [comment]
Apparently, I am still living in 2020. AmxModX doesn't seem to crash with BunnymodXT anymore??? Okay.

**Comment by SmileyAG** [comment]
I think you can simply check inside **liblist.gam** for `gamedll` and `gamedll_linux` keyvalues whether **metamod** is contained in string during the server module initialization, and if it success then give an error message box and crash the game so that a person must start without it

Or if metamod exporting some own functions, then we can intercept it by symbol and give an error message box and crash the game

**Comment by khanghugo** [comment]
I did have a working implementation. But then once I accidentally have it not working, my game doesn't crash... Currently BXT server DLL has to inject like 10 times. I asked someone else to test and the combo doesn't crash for them either.

**Comment by khanghugo** [comment]
The implementation is just checking for input string of `LoadThisDll` and do string manipulation. I am not sure if I should pursue this because it is not a problem right now.

**Comment by SmileyAG** [comment]
> The implementation is just checking for input string of `LoadThisDll` and do string manipulation

This approach is bad, since you don’t have the data to know what exactly needs to be loaded instead of that addon, so you trying to guess it based on what game directory is set.

Instead of solving this issue for the user, in my opinion it is much preferable to simply throw an error and close the game (so the user has to do it himself), this way you also save yourself from extra manipulations and do not make tool even more dependent on support

**Comment by khanghugo** [comment]
That's the issue I was trying to fix. The problem is that people might have a reason to run AmxModX. In CS 1.6 KZ, in order to submit a KZ demo, they must record it with some plugins. Some players happen to be mappers. BunnymodXT has a lot useful features. Mappers might want to consider BunnymodXT. But BunnymodXT crashes with AmxModX due to MetaMod (which is NOT the case anymore). So they need to change liblist.gam file. When they want to use AmdModX again, they have to change the file.

That is very inconvenient. That is why I want to make it automatically disable for people. AmdModX is only popular for CS 1.6 and maybe maybe maybe Half-Life for people running LAN server. That is why I only need to target a few mods. 

Regardless, it doesn't crash any more for some reasons because I remember the reason why I never use AmxModX because it crashes with BunnymodXT.

**Comment by khanghugo** [comment]
Apparently, someone told me that game crashes when BXT is with AmxModX. Maybe this is needed. 

You don't want the implementation I suggested? I am just trying to solve this a bit differently because it really makes things hassle-free. I can have a PR with that if you think it is okay.

**Comment by SmileyAG** [comment]
> Apparently, someone told me that game crashes when BXT is with AmxModX. Maybe this is needed.
> 
> You don't want the implementation I suggested? I am just trying to solve this a bit differently because it really makes things hassle-free. I can have a PR with that if you think it is okay.

You know, if this is so important, then we can make an exception for Counter-Strike, in the form that if we detect the `cstrike` game directory and the metamod library loaded, then **mp.dll** or **cstrike.so** will be loaded instead of metamod

But in all other cases, if a user has metamod detected as loaded, you don’t need to fix anything for him, just close the game for him with a error message so that he must to fix it himself, this is a really simple and working method that does not require unnecessary spaghetti in the code, because common, commenting out or uncommenting one line in `liblist.gam` does not require much effort and time
