### ISSUE TITLE
SDL2 and libSDL2 error when using HLSR to inject BXT

### ISSUE THREAD

**Issue by aknetia** [YaLTeR/BunnymodXT#513]
Game freezes and stops responding after launch with a consistent error in the debug console "SPTLib: Unable to obtain the SDL2.dll module info!" and "SPTLib: Unable to obtain the libSDL2-2.0.so.0 module info!". SDL2.dll is installed, I've restarted my PC and reinstalled Visual C++ Redistributable via vc_redist.x86.exe. Non of these have solved my problem. Something that could possibly be causing the problem is that I am using HLSR to inject BXT meaning this could either be a problem with HLSR or BXT.

![Screenshot 2024-03-09 151324](https://github.com/YaLTeR/BunnymodXT/assets/162844895/fcf5e961-7dfe-4c28-8ef8-94b5d8d3c1b3)

**Comment by YaLTeR** [comment]
That error sounds unrelated. Maybe something in HLSR.

**Comment by SmileyAG** [comment]
By error means that these libraries are also not in the game directory, therefore this engine was likely released before Steampipe, and therefore it is not linked to SDL2 (i.e. copying libraries will not help, because game wouldn't even know about SDL2, and the fact that the BXT code did not find SDL2 is not a critical issue at all)

GoldSrc engine started using SDL2 with the release of the Steampipe version of the engine, which means that starting from 2013 year (59xx+ builds)

If this error is on the HLSR side, then we obviously can't do anything about it
It’s better to try using other speedrun builds or inject into the game directly itself, bypassing the extra steps in the form of custom launchers like HLSR
Here is a link to a more common and cleaner package that used among the speedrun community: https://forums.sourceruns.org/t/goldsrc-package-2-4/2634

For more questions related to speedruns and the launch of the game in general, please ask in #goldsrc-help of SourceRuns Discord server: https://discord.gg/sourceruns

This tracker is more used to suggest adding new functionality or when the bug is clearly on the BXT side (e.g. crashes or missing commands in some unique mods)
